// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     email-message.json
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

func writeArrayEmailBodyPart(r []*EmailBodyPart, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeEmailBodyPart(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayEmailBodyPartWrapper struct {
	Target *[]*EmailBodyPart
}

func (_ *ArrayEmailBodyPartWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayEmailBodyPartWrapper) Finalize()                        {}
func (_ *ArrayEmailBodyPartWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayEmailBodyPartWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayEmailBodyPartWrapper) AppendArray() types.Field {
	var v *EmailBodyPart
	v = NewEmailBodyPart()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
