// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     email-message.json
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type EmailSource int32

const (
	EmailSourceAppleAppStore EmailSource = 0
	EmailSourceGOG           EmailSource = 1
)

func (e EmailSource) String() string {
	switch e {
	case EmailSourceAppleAppStore:
		return "AppleAppStore"
	case EmailSourceGOG:
		return "GOG"
	}
	return "unknown"
}

func writeEmailSource(r EmailSource, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewEmailSourceValue(raw string) (r EmailSource, err error) {
	switch raw {
	case "AppleAppStore":
		return EmailSourceAppleAppStore, nil
	case "GOG":
		return EmailSourceGOG, nil
	}

	return -1, fmt.Errorf("invalid value for EmailSource: '%s'", raw)
}

func (b *EmailSource) MarshalJSON() ([]byte, error) {
	return json.Marshal([]byte(b.String()))
}

func (b *EmailSource) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewEmailSourceValue(stringVal)
	*b = val
	return err
}

type EmailSourceWrapper struct {
	Target *EmailSource
}

func (b *EmailSourceWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b *EmailSourceWrapper) SetInt(v int32) {
	*(b.Target) = EmailSource(v)
}

func (b *EmailSourceWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b *EmailSourceWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b *EmailSourceWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b *EmailSourceWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b *EmailSourceWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b *EmailSourceWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b *EmailSourceWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b *EmailSourceWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b *EmailSourceWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b *EmailSourceWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b *EmailSourceWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b *EmailSourceWrapper) Finalize() {}
