// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     email-message.json
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/container"
	"github.com/actgardner/gogen-avro/v7/vm"
)

func NewEmailBodyPartWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewEmailBodyPart()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type EmailBodyPartReader struct {
	r io.Reader
	p *vm.Program
}

func NewEmailBodyPartReader(r io.Reader) (*EmailBodyPartReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewEmailBodyPart()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &EmailBodyPartReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r EmailBodyPartReader) Read() (*EmailBodyPart, error) {
	t := NewEmailBodyPart()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
